version: '3'

services:

  producer:
    build: 
      context: ./producer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC: topic-test
      PYTHONUNBUFFERED: 1

  consumer:
    build: 
      context: ./consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC: topic-test
      PYTHONUNBUFFERED: 1

networks:
  default:
    external:
      name: kafka-network